global:
  scrape_interval: 15s # when Prometheus is pulling data from exporters etc
  evaluation_interval: 30s # time between each evaluation of Prometheus' alerting rules

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: model_registry
    scrape_interval: 5m
    scrape_timeout: 1m
    metrics_path: '/'
    static_configs:
      - targets: ['model_registry:8000']
